name: Test

on: 
 pull_request:
   types: [opened, synchronize, reopened]
 push:
   branches:
     - master


jobs:
  docker:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - ruby-version: '3.2'
            fixture-schema: 'v1'
            registry-image: 'registry:2.8.3'
          - ruby-version: '3.2'
            fixture-schema: 'v2'
            registry-image: 'registry'
          - ruby-version: '3.3'
            fixture-schema: 'v1'
            registry-image: 'registry:2.8.3'
          - ruby-version: '3.3'
            fixture-schema: 'v2'
            registry-image: 'registry'
          - ruby-version: '3.4'
            fixture-schema: 'v1'
            registry-image: 'registry:2.8.3'
          - ruby-version: '3.4'
            fixture-schema: 'v2'
            registry-image: 'registry'
          - ruby-version: '4.0'
            fixture-schema: 'v1'
            registry-image: 'registry:2.8.3'
          - ruby-version: '4.0'
            fixture-schema: 'v2'
            registry-image: 'registry'
    steps:
    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Checkout
      uses: actions/checkout@v1

    - name: Start containers
      env:
        REGISTRY_IMAGE: ${{ matrix.registry-image }}
      run: docker compose -f "docker-compose.yml" up -d --build

    - name: bundle install
      run: bundle install
    
    - name: Run tests
      run: REGISTRY=http://localhost:5000 VERSION=${{ matrix.fixture-schema }} ruby ./test/test.rb

    - name: Stop containers
      if: always()
      env:
        REGISTRY_IMAGE: ${{ matrix.registry-image }}
      run: docker compose -f "docker-compose.yml" down
